ETA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from signup import views

urlpatterns = [
    url(r'^tournaments/', include('tournaments.urls')),
    url(r'^teams/', include('teams.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^home/$', views.home, name='home'),
]

teams/urls.py
from django.conf.urls import url

from . import views

app_name = 'teams'
urlpatterns = [
    url(r'^$', views.TeamsView.as_view(), name='teams'),
    url(r'^new/$', views.createTeam, name='create_team'),
    url(r'^(?P<pk>[0-9]+)/$', views.TeamDetailView.as_view(), name='details'),
    url(r'^addmember/$', views.addMembers, name='add_members')
]

teams/models.py
from django.db import models
from django.contrib.auth.models import User

class Team(models.Model):
    founder = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=32)
    abbreviaton = models.CharField(max_length=4)

class TeamMembers(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(User, editable=True)

teams/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User

from teams.models import Team, TeamMembers

class TeamsView(generic.ListView):
    template_name = 'teams/teams.html'
    context_object_name = 'user_teams'

    def get_queryset(self):
        """Return teams, in which current user is registered."""
        team_member = Team.objects.filter(teammembers__user=self.request.user)
        team_founder = Team.objects.filter(founder=self.request.user)
        teams = team_member | team_founder
        return teams

def createTeam(request):
    """
    Create team model and save given data from AJAX form and redirect to its
    detail view.
    """
    if request.method == 'POST':
        team_name = request.POST['team-name']
        team_abbr = request.POST['team-abbr']
        user = request.user
        status = 1
        message = 'Ok'
        if (not Team.objects.filter(name=team_name).exists()):
            team = Team.objects.create(
                founder = user,
                name = team_name,
                abbreviaton = team_abbr)
            url = reverse('teams:details', args=(team.id,))
        else:
            status = 0
            message = 'Team name already registered, please choose another.'
            url = None
    response = {'status': status, 'message': message, 'url': url}
    return HttpResponse(json.dumps(response), content_type='application/json')

def addMembers(request):
    #TODO: create invitation member adding system
    """
    add given member to the given team.
    """
    if request.method == 'POST':
        member_name = request.POST['member-name']
        team_id = request.POST['team-pk']
        current_user = request.user
        team = Team.objects.get(pk=team_id)
        status = 1
        message = 'User successfully added to the team'
        if (team.founder == current_user):
            #TODO: user DoesNotExist exception
            try:
                new_member_user = User.objects.get(username=member_name)
                if (not team.teammembers_set.filter(user=new_member_user)):
                    team.teammembers_set.create(user=new_member_user)
                else:
                    status = 0
                    message = "User already added to team"
            except User.DoesNotExist:
                status = 0
                message = "User does not exist."
        else:
            status = 0
            message = 'Not authorized for this action.'

    response = {'status': status, 'message': message}
    return HttpResponse(json.dumps(response), content_type='application/json')

class TeamDetailView(generic.DetailView):
    model = Team
    template_name = 'teams/details.html'

teams/templates/teams/details.html
{% extends 'header.html' %}
{% load staticfiles %}

{% block title %}{{ team.name }}{% endblock %}
{% block content %}
<script src="{% static 'teams/js/add_member.js' %}"></script>
<h1>{{ team.name }}</h1>
<h3>Team members: </h3>
<p>Founder: {{ team.founder }}</p>
{% for member in team.teammembers_set.all %}
  <p>{{ member.user }}</p>
{% endfor %}

{% if user == team.founder %}
<form id="add-members" action="{% url 'teams:add_members' %}" method="post">
  {% csrf_token %}
  <label for="member-name">Member name:</label>
  <br />
  <input type="text" id="member-name" name="member-name" maxlength="150" required/>
  <br />
  <input type="hidden" id="team-pk" name="team-pk" value="{{team.pk}}"/>
  <input type="submit" value="add new member"/>
</form>
{% endif %}
{% endblock %}

teams/templates/teams/teams.html
{% extends 'header.html' %}
{% load staticfiles %}

{% block title %}Teams{% endblock %}
{% block content %}
<script src="{% static 'teams/js/save_team.js' %}"></script>
<form id="create-team" action="{% url 'teams:create_team' %}" method="post">
  {% csrf_token %}
  <label for="team-name">Team name:</label><br />
  <input type="text" id="team-name" name="team-name" maxlength="32" required/><br />

  <label for="team-abbr">Team abbreviaton:</label><br />
  <input type="text" id="team-abbr" name="team-abbr" maxlength="32" required/><br />
  <input type="submit" value="Create new team"/>
</form>
<div id="Teams list">
  <h3>Your teams:</h3>
  {% for team in user_teams %}
  <a href="{% url 'teams:details' team.id %}">{{ team.name }}</a>
  <br />
  {% endfor %}
</div>
{% endblock %}