ETA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from signup import views

urlpatterns = [
    url(r'^tournaments/', include('tournaments.urls')),
    url(r'^teams/', include('teams.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^home/$', views.home, name='home'),
]

teams/urls.py
from django.conf.urls import url

from . import views

app_name = 'teams'
urlpatterns = [
    url(r'^$', views.TeamsView.as_view(), name='teams'),
    url(r'^new/$', views.createTeam, name='create_team'),
    url(r'^(?P<pk>[0-9]+)/$', views.TeamDetailView.as_view(), name='details'),
    url(r'^addmember/$', views.addMembers, name='add_members')
]

tournaments/urls.py
from django.conf.urls import url

from . import views

app_name = 'tournaments'
urlpatterns = [
    url(r'^$', views.TournamentsView.as_view(), name='tournaments'),
    url(r'^(?P<pk>[0-9]+)/$', views.TournamentDetailView.as_view(), name='details'),
    url(r'^new/$', views.createTournament, name='create_tournament'),
    url(r'^search/$', views.searchTournament, name='search_tournament'),
    url(r'^apllications/$', views.teamApplications, name='team_applications'),
    url(r'^apply/$', views.teamApply, name='team_apply')
]

tournaments/models.py
from django.db import models
from django.contrib.auth.models import User

from teams.models import Team

class Tournament(models.Model):
    organizer = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=63)
    description = models.TextField()
    tournament_date = models.DateField()
    address = models.CharField(max_length=255)

class TournamentApplication(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)

class TournamentTeams(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)

tournaments/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic

from tournaments.models import Tournament, TournamentApplication, TournamentTeams
from teams.models import Team

class TournamentsView(generic.ListView):
    """
    Generate tournaments view passing all registered tournaments.
    """
    template_name = 'tournaments/tournaments.html'
    context_object_name = 'tournaments'
    model = Tournament

def createTournament(request):
    """
    Create tournament model object and save.
    """
    if request.method == 'POST':
        name = request.POST['tournament-name']
        desc = request.POST['tournament-desc']
        date = request.POST['tournament-date']
        address = request.POST['tournament-address']
        organizer = request.user
        status = 1
        message = 'Ok'

        if (not Tournament.objects.filter(name=name).exists()):
            tournament = Tournament.objects.create(
                organizer = organizer,
                name = name,
                description = desc,
                tournament_date = date,
                address = address
            )
            url = reverse('tournaments:details', args=(tournament.id,))
        else:
            status = 0
            message = 'Tournament name already registered, please choose another'
            url = None
        response = {'status': status, 'message': message, 'url': url}
        return HttpResponse(json.dumps(response), content_type='application/json')

def searchTournament(request):
    """
    Find tournaments by name, render results view.
    """
    results = None
    if request.method == 'POST':
        query = request.POST['tournament-search']
        results = Tournament.objects.filter(name__contains=query)
    return render(request, 'tournaments/results.html', {'results': results})

def teamApplications(request):
    """
    Handle request to accept or deny team applications to join tournament.
    """
    status = 1
    message = "Successfully applied"
    if request.method == 'POST':
        team_ids = request.POST.getlist('team-applications[]')
        tournament_id = request.POST['tournament-id']
        button = request.POST.getlist('accept')
        for team_id in team_ids:
            team = Team.objects.get(id=team_id)
            tournament = Tournament.objects.get(id=tournament_id)
            tournamentapplication = TournamentApplication.objects.get(
                team = team,
                tournament = tournament
            )
            tournamentapplication.delete()
            if 'accept' in request.POST:
                tournament.tournamentteams_set.create(team=team)

    response = {'status': status, 'message': message}
    return HttpResponse(json.dumps(response), content_type='application/json')

def teamApply(request):
    """
    Handle request to apply for a tournament
    """
    status = 1
    message = "Successfully applied"
    if request.method == 'POST':
        team_ids = request.POST.getlist('teams[]')
        tournament_id = request.POST['tournament_id']
        for team_id in team_ids:
            team = Team.objects.get(id=team_id)
            tournament = Tournament.objects.get(id=tournament_id)
            tournament.tournamentapplication_set.create(team=team)
    response = {'status': status, 'message': message}
    return HttpResponse(json.dumps(response), content_type='application/json')

class TournamentDetailView(generic.TemplateView):
    template_name = 'tournaments/details.html'

    def get_context_data(self, **kwargs):
        """
        Return context with requested tournament and queryset of teams that current
        user is founder of and which aren't registered as accepted or applied teams.
        """
        context = super(TournamentDetailView, self).get_context_data(**kwargs)
        context['tournament'] = Tournament.objects.get(id=self.kwargs['pk'])
        context['teams'] = Team.objects.filter(
            founder=self.request.user
        ).exclude(
            tournamentapplication__team__id__in=TournamentApplication.objects.all().values_list('team__id')
        ).exclude(
            tournamentteams__team__id__in=TournamentTeams.objects.all().values_list('team__id')
        )
        return context

tournaments/templates/tournaments/details.html
{% extends 'header.html' %}
{% load staticfiles %}

{% block title %}{{ tournament.name }}{% endblock %}
{% block content %}
<script src="{% static 'tournaments/js/team_applications.js' %}"></script>
<div class="container">
  <div class="row">
    <div class="col">
      <h1>{{ tournament.name }}</h1>
      <h6>Description:</h6>
      <p>{{ tournament.description }}</p>
      <h6>Where it's happening:</h6>
      <p>{{ tournament.address }}</p>
      <h6>Date:</h6>
      <p>{{ tournament.tournament_date }}</p>
    </div>

    <div class="col">
      <h3>Registered teams:</h3>
      <ul>
        {% for application in tournament.tournamentteams_set.all %}
          <li><a href="{% url 'teams:details' application.team.id %}">{{ application.team.name }}</a></li>
        {% endfor %}
      </ul>
    </div>

    <div class="col">
      {% if user == tournament.organizer %}
        <h3>Team Applications:</h3>
        {% if tournament.tournamentapplication_set.all %}
          <form id="team-applications" action="{% url 'tournaments:team_applications' %}" method="post">
            {% csrf_token %}
            {% for application in tournament.tournamentapplication_set.all %}
            <div class="team-application">
              <a href="{% url 'teams:details' application.team.id %}">{{ application.team.name }}</a>
              <input type="checkbox" name="team-applications[]" value="{{ application.team.id }}"/>
            </div>
            {% endfor %}
            <input type="hidden" name="tournament-id" value="{{ tournament.id }}" />
            <input type="submit" class="application-submit btn btn-success" name="accept" value="accept" />
            <input type="submit" class="application-submit btn btn-danger" name="deny" value="deny" />
          </form>
        {% else %}
          <p>No teams have applied</p>
        {% endif %}
      {% elif teams %}
        <h3>Apply with team:</h3>
        <form id="team-apply" action="{% url 'tournaments:team_apply' %}" method="post">
          {% for team in teams %}
              {% csrf_token %}
              <div class="team">
                <span>{{ team.name }}</span>
                <input type="checkbox" name="teams[]" value="{{ team.id }}"/>
                <input type="hidden" name="tournament_id" value="{{ tournament.id }}" />
              </div>
              <br />
          {% endfor %}
          <input type="submit" value="Apply" />
        </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

tournaments/templates/tournaments/results.html
{% extends 'header.html' %}

{% block title %}Tournament search{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <h3>Search for tournament</h3>
      <form id="search-tournaments" action="{% url 'tournaments:search_tournament' %}" method="post">
        {% csrf_token %}
        <input type="text" name="tournament-search" />
        <input type="submit" value="Search" />
      </form>
      <ul>
        {% for tournament in results %}
          <li><a href="{% url 'tournaments:details' tournament.id %}">{{ tournament.name }}</a>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

{% endblock %}

tournaments/templates/tournaments/tournaments.html
{% extends 'header.html' %}
{% load staticfiles %}

{% block title %}Tournaments{% endblock %}

{% block head %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% endblock %}

{% block content %}
<script src="{% static 'tournaments/js/create_tournament.js' %}"></script>
<div class="container">
  <div class="row">

    <div class="col">
      <h3>Create new tournament:</h3>
      <form id="create-tournaments" action="{% url 'tournaments:create_tournament' %}" method="post">
        {% csrf_token %}
        <label for="tournament-name">Tournament name:</label>
        <br />
        <input type="text" id="tournament-name" name="tournament-name" maxlength="63" required/>
        <br />

        <label for="tournament-desc">Description:</label>
        <br />
        <textarea id="tournament-desc" name="tournament-desc" required></textarea>
        <br />

        <label for="tournaments-abbr">Date:</label>
        <br />
        <input type="text" id="tournament-date" name="tournament-date" required/>
        <br />

        <label for="tournament-address">Address:</label>
        <br />
        <textarea id="tournament-address" name="tournament-address" maxlength="255" required></textarea>
        <br />
        <input type="submit" value="Create new tournament"/>
      </form>
    </div>

    <div class="col">
      <h3>Latest Tournaments:</h3>
      <ul>
        {% for tournament in tournaments %}
          <li><a href="{% url 'tournaments:details' tournament.id %}">{{ tournament.name }}</a>
        {% endfor %}
      </ul>
    </div>

    <div class="col">
      <h3>Search for tournament</h3>
      <form id="search-tournaments" action="{% url 'tournaments:search_tournament' %}" method="post">
        {% csrf_token %}
        <input type="text" name="tournament-search" />
        <input type="submit" value="Search" />
      </form>
    </div>
  </div>
</div>
{% endblock %}