ETA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from signup import views

urlpatterns = [
    url(r'^tournaments/', include('tournaments.urls')),
    url(r'^teams/', include('teams.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^home/$', views.home, name='home'),
]

teams/urls.py
from django.conf.urls import url

from . import views

app_name = 'teams'
urlpatterns = [
    url(r'^$', views.TeamsView.as_view(), name='teams'),
    url(r'^new/$', views.createTeam, name='create_team'),
    url(r'^(?P<pk>[0-9]+)/$', views.TeamDetailView.as_view(), name='details'),
    url(r'^addmember/$', views.addMembers, name='add_members')
]

tournaments/urls.py
from django.conf.urls import url

from . import views

app_name = 'tournaments'
urlpatterns = [
    url(r'^$', views.TournamentsView.as_view(), name='tournaments'),
    url(r'^(?P<pk>[0-9]+)/$', views.TournamentDetailView.as_view(), name='details'),
    url(r'^new/$', views.createTournament, name='create_tournament'),
    url(r'^search/$', views.searchTournament, name='search_tournament'),
    url(r'^apllications/$', views.teamApplications, name='team_applications'),
    url(r'^apply/$', views.teamApply, name='team_apply')
]

templates/header.html
<!DOCTYPE html>

<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  {% block head %}
  {% endblock %}
</head>
</body>
<header>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'teams:teams' %}">Teams</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tournaments:tournaments' %}">Tournaments</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout_view' %}">Log out</a>
        </li>
      </ul>
    </div>
  </nav>
</header>
{% block content %}
{% endblock %}
<body>